apiVersion: v1
kind: Pod
metadata:
  name: oracle-db-pod
spec:
  containers:
  - name: oracle-container
    image: doctorkirk/oracle-19c
    resources:
      limits:
        memory: 2Gi
        cpu: 2
    volumeMounts:
      - name: oracle-data
        mountPath: /opt/oracle/oradata
  volumes:
    - name: oracle-data
      persistentVolumeClaim:
        claimName: oracle-data-pvc
  ports:
    - containerPort: 1521
    - containerPort: 5500
  env:
    - name: ORACLE_SID
      value: ORCL
    - name: ORACLE_PDB
      value: ORCLPDB1
    - name: ORACLE_PWD
      valueFrom:
        secretKeyRef:
          name: oracle-secret
          key: oracle-password
